manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: e68abe57d8b63219343c206f9116a70b150a9df4 # main
      import: app/west.yml
  self:
    path: config
